-- AlterTable
ALTER TABLE `audit_logs` MODIFY `action` ENUM('PAYMENT_CREATED', 'PAYMENT_PROCESSING', 'PAYMENT_SUCCEEDED', 'PAYMENT_FAILED', 'WEBHOOK_RECEIVED', 'WEBHOOK_REJECTED', 'WEBHOOK_DUPLICATE', 'REFUND_REQUESTED', 'REFUND_SUCCEEDED', 'REFUND_FAILED', 'UNAUTHORIZED_PAYMENT_ACCESS', 'SUSPICIOUS_PAYMENT_MISMATCH', 'PAYMENT_RECONCILED', 'USER_STATUS_CHANGED', 'AUTO_APPROVAL_FAILED') NOT NULL;
