"""Generates public/img/hero-schematic.svg — the drawing behind the hero.

Authored rather than photographed, and that is forced as well as preferred:
img-src on this site is 'self' plus data:, so a stock photograph from any CDN
is blocked outright, and an uploaded one is wiped by the next deploy. A vector
ships with the code, weighs a few kilobytes, and stays sharp from a phone to a
4K monitor.

What it draws is a real gear-train sheet: a spur gear and its meshing pinion,
on centre lines, with a bolt circle, a diameter dimension and section hatching
— the conventions an ME student actually sees on a drawing, not gear-shaped
clip art.
"""
import math

W = H = 640

# The assembly: a gear is (centre x, centre y, pitch radius, tooth count).
GEAR_X, GEAR_Y, GEAR_R, GEAR_N = 250.0, 300.0, 168.0, 28
PIN_R, PIN_N = 84.0, 14
# Meshing means the pitch circles are tangent: centres sit exactly r1+r2 apart.
ANG = math.radians(-24.0)
PIN_X = GEAR_X + (GEAR_R + PIN_R) * math.cos(ANG)
PIN_Y = GEAR_Y + (GEAR_R + PIN_R) * math.sin(ANG)

out = []
a = out.append


# --- stroke vocabulary ---------------------------------------------------
#
# Written as presentation ATTRIBUTES rather than as a <style> block inside the
# SVG, and that is load-bearing. This file is served as a static asset, so it
# carries the site's own CSP, whose style-src is 'self' plus a nonce. An inline
# <style> in here would have no nonce and would be dropped — and since every
# shape is fill="none", losing the strokes means the drawing renders as
# literally nothing. Presentation attributes are not covered by style-src.
STYLES = {
    # the part itself
    "outline": 'stroke="#efd280" stroke-opacity=".92" stroke-width="1.6"',
    # construction and hidden detail
    "constr": 'stroke="#ffffff" stroke-opacity=".30" stroke-width="1"',
    # centre lines, dash-dot, the drafting convention
    "centre": 'stroke="#ffffff" stroke-opacity=".45" stroke-width="1" stroke-dasharray="14 4 2 4"',
    # dimensions and their witness lines
    "dim": 'stroke="#efd280" stroke-opacity=".7" stroke-width="1"',
    "lbl": ('fill="#efd280" fill-opacity=".85" font-size="11" font-weight="600" '
            'letter-spacing=".9" font-family="ui-monospace,Consolas,monospace"'),
}


def st(name):
    return STYLES[name]


def fmt(v):
    return f"{v:.2f}".rstrip("0").rstrip(".")


def teeth_path(cx, cy, r, n, height, phase=0.0):
    """A trapezoidal tooth ring. Not an involute — at this scale the flank
    curve is under a pixel, and the silhouette is what reads."""
    ro = r + height * 0.55
    ri = r - height * 0.45
    step = 2 * math.pi / n
    # Tooth occupies 44% of the pitch, the space between them the rest.
    half_top = step * 0.22
    half_base = step * 0.30
    d = []
    for i in range(n):
        c = phase + i * step
        pts = [
            (ri, c - step / 2 + (step / 2 - half_base)),
            (ro, c - half_top),
            (ro, c + half_top),
            (ri, c + step / 2 - (step / 2 - half_base)),
        ]
        # Walk the root arc to the next tooth so the ring is one closed path.
        for j, (rad, ang) in enumerate(pts):
            x = cx + rad * math.cos(ang)
            y = cy + rad * math.sin(ang)
            d.append(("M" if (i == 0 and j == 0) else "L") + f"{fmt(x)} {fmt(y)}")
        nxt = c + step
        x = cx + ri * math.cos(nxt - step / 2 - (step / 2 - half_base))
        y = cy + ri * math.sin(nxt - step / 2 - (step / 2 - half_base))
        d.append(f"L{fmt(x)} {fmt(y)}")
    return " ".join(d) + " Z"


def circle(cx, cy, r, cls):
    return f'<circle cx="{fmt(cx)}" cy="{fmt(cy)}" r="{fmt(r)}" {st(cls)}/>'


def line(x1, y1, x2, y2, cls):
    return f'<line x1="{fmt(x1)}" y1="{fmt(y1)}" x2="{fmt(x2)}" y2="{fmt(y2)}" {st(cls)}/>'


a(f'<svg xmlns="http://www.w3.org/2000/svg" width="{W}" height="{H}" '
  f'viewBox="0 0 {W} {H}" fill="none" role="img" '
  f'aria-label="Engineering drawing of a spur gear meshing with its pinion">')
a("""  <!--
    GENERATED by scripts/gen_schematic.py — edit that, not this.

    Every stroke is one of four weights, which is what makes it read as a
    drawing rather than as decoration:
      .outline  the part itself
      .constr   construction and hidden detail
      .centre   centre lines, dash-dot, the drafting convention
      .dim      dimensions and their witness lines
  -->""")
a("""  <defs>
    <pattern id="hatch" width="7" height="7" patternUnits="userSpaceOnUse" patternTransform="rotate(45)">
      <line x1="0" y1="0" x2="0" y2="7" stroke="#efd280" stroke-opacity=".55" stroke-width="1"/>
    </pattern>
    <marker id="ar" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">
      <path d="M0 0 L10 5 L0 10 z" fill="#efd280" fill-opacity=".85"/>
    </marker>
  </defs>
  """)

# --- the gear -----------------------------------------------------------
a('  <g>')
a(f'    <path d="{teeth_path(GEAR_X, GEAR_Y, GEAR_R, GEAR_N, 26)}" {st("outline")}/>')
a("    " + circle(GEAR_X, GEAR_Y, GEAR_R, "constr"))          # pitch circle
a("    " + circle(GEAR_X, GEAR_Y, GEAR_R - 42, "outline"))    # web
a("    " + circle(GEAR_X, GEAR_Y, 54, "outline"))             # hub
a("    " + circle(GEAR_X, GEAR_Y, 30, "outline"))             # bore
# Keyway on the bore, because a gear that cannot transmit torque is an ornament.
a(f'    <path d="M{fmt(GEAR_X-9)} {fmt(GEAR_Y-30)} L{fmt(GEAR_X-9)} {fmt(GEAR_Y-40)} '
  f'L{fmt(GEAR_X+9)} {fmt(GEAR_Y-40)} L{fmt(GEAR_X+9)} {fmt(GEAR_Y-30)}" {st("outline")}/>')
# Bolt circle: six lightening holes on a construction circle.
BOLT_R = GEAR_R - 86
a("    " + circle(GEAR_X, GEAR_Y, BOLT_R, "centre"))
for i in range(6):
    t = math.radians(i * 60 + 15)
    hx, hy = GEAR_X + BOLT_R * math.cos(t), GEAR_Y + BOLT_R * math.sin(t)
    a("    " + circle(hx, hy, 13, "outline"))
    a("    " + line(hx - 19, hy, hx + 19, hy, "centre"))
    a("    " + line(hx, hy - 19, hx, hy + 19, "centre"))
# A quadrant of the web in section.
a(f'    <path d="M{fmt(GEAR_X)} {fmt(GEAR_Y)} L{fmt(GEAR_X + GEAR_R-42)} {fmt(GEAR_Y)} '
  f'A{fmt(GEAR_R-42)} {fmt(GEAR_R-42)} 0 0 1 {fmt(GEAR_X)} {fmt(GEAR_Y + GEAR_R-42)} Z" '
  f'fill="url(#hatch)" fill-opacity=".5" stroke="none"/>')
a('  </g>')

# --- the pinion ---------------------------------------------------------
a('  <g>')
a(f'    <path d="{teeth_path(PIN_X, PIN_Y, PIN_R, PIN_N, 26, phase=math.pi/PIN_N)}" {st("outline")}/>')
a("    " + circle(PIN_X, PIN_Y, PIN_R, "constr"))
a("    " + circle(PIN_X, PIN_Y, 34, "outline"))
a("    " + circle(PIN_X, PIN_Y, 18, "outline"))
a('  </g>')

# --- centre lines -------------------------------------------------------
a("  " + line(GEAR_X - GEAR_R - 60, GEAR_Y, GEAR_X + GEAR_R + 60, GEAR_Y, "centre"))
a("  " + line(GEAR_X, GEAR_Y - GEAR_R - 60, GEAR_X, GEAR_Y + GEAR_R + 60, "centre"))
a("  " + line(PIN_X - PIN_R - 40, PIN_Y, PIN_X + PIN_R + 40, PIN_Y, "centre"))
a("  " + line(PIN_X, PIN_Y - PIN_R - 40, PIN_X, PIN_Y + PIN_R + 40, "centre"))
# The centre distance, which is the one dimension a gear pair is defined by.
a("  " + line(GEAR_X, GEAR_Y, PIN_X, PIN_Y, "centre"))

# --- dimensions ---------------------------------------------------------
# Pitch diameter of the gear, dimensioned below it with witness lines.
DY = GEAR_Y + GEAR_R + 54
a("  " + line(GEAR_X - GEAR_R, GEAR_Y, GEAR_X - GEAR_R, DY + 8, "dim"))
a("  " + line(GEAR_X + GEAR_R, GEAR_Y, GEAR_X + GEAR_R, DY + 8, "dim"))
a(f'  <line x1="{fmt(GEAR_X-GEAR_R)}" y1="{fmt(DY)}" x2="{fmt(GEAR_X+GEAR_R)}" y2="{fmt(DY)}" '
  f'{st("dim")} marker-start="url(#ar)" marker-end="url(#ar)"/>')
a(f'  <rect x="{fmt(GEAR_X-38)}" y="{fmt(DY-9)}" width="76" height="18" fill="#131131" fill-opacity=".85"/>')
a(f'  <text x="{fmt(GEAR_X)}" y="{fmt(DY+4)}" text-anchor="middle" {st("lbl")}>&#216; 336</text>')

# Leader off a tooth, naming the module and count — the two numbers that
# actually specify a spur gear.
tx = GEAR_X + (GEAR_R + 16) * math.cos(math.radians(-116))
ty = GEAR_Y + (GEAR_R + 16) * math.sin(math.radians(-116))
a(f'  <path d="M{fmt(tx)} {fmt(ty)} L{fmt(tx-46)} {fmt(ty-40)} L{fmt(tx-138)} {fmt(ty-40)}" {st("dim")}/>')
a(f'  <text x="{fmt(tx-134)}" y="{fmt(ty-48)}" {st("lbl")}>m 12 &#183; z {GEAR_N}</text>')

a(f'  <text x="{fmt(PIN_X+PIN_R+18)}" y="{fmt(PIN_Y-PIN_R-6)}" {st("lbl")}>z {PIN_N}</text>')

a('</svg>')

import io, os
path = os.path.join('public', 'img', 'hero-schematic.svg')
io.open(path, 'w', encoding='utf-8').write("\n".join(out) + "\n")
print('wrote', path, os.path.getsize(path), 'bytes')
